name: Server push update

on: 
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
  

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
         
        - name: Set up SSH
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.DEPLOY_KEY }}" | base64 -d > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan strangers.pub >> ~/.ssh/known_hosts
      
        - name: Pull code on remote server
          run: |
            ssh -vvv -i ~/.ssh/id_rsa kdizzled@strangers.pub "
            cd /home/kdizzled/server/logical-fallacy-detection && 
            git pull origin main && 
            chmod +x ./deploy.sh && 
            ./deploy.sh"
